#working with list 
fruits = ['mango','pinapple','water melon','banana','apple','mango']
print(fruits)
fruits.append('avacado')
print(fruits)
fruits.insert(0,'kiwi')
print(fruits)
vegitables = ['potato','carret','onion']
print(vegitables)
fruits.extend(vegitables)
print(fruits)
fruits.remove('onion')
print(fruits)
fruits.pop(0)
print(fruits)
fruits.sort()
print(fruits)
fruits.reverse()
print(fruits)
fruits2 = fruits.copy()
print(fruits2)
fruits2.clear()
print(fruits)
pos = fruits.index("potato")
print(pos)
# pos = fruits.index("orange")
# print(pos)
count = fruits.count("mango")
print(count)